config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show
   @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>

  <body>
    <div class="container py-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="d-flex">
  <%= form_with model: @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
    <hr>
    <%= f.submit class: 'btn btn-outline-primary' %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>Task Manager</h1>
<h2>Task List by Title</h2>
<hr>
<% @tasks.each do |task| %>
    <p><%= link_to task.title, task_path(task), class: 'text-decoration-none' %></p>
  <% end %>
<hr>
<%= link_to "Add Task", new_task_path, class: 'btn btn-outline-primary' %>

app/views/tasks/new.html.erb
<h1>Add New Task</h1>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1>Task Title: <%= @task.title %></h1>
<p>Details: <%= @task.details %> | Completed: <%= @task.completed %> </p>
<hr>
<%= link_to "Back to List", tasks_path, class: 'btn btn-outline-primary' %>
<%= link_to "Edit Task", edit_task_path, class: 'btn btn-outline-primary' %>
<%= link_to "Delete",
  task_path, class: 'btn btn-outline-primary',
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>